### PR TITLE
Fix deploy with no constructor

### LINKED ISSUE #828: `warp deploy_account` doesn't seem to work anymore
```
warp deploy_account
Error: AssertionError:
starknet deploy failed
```

### LINKED ISSUE #829: Deploy with no constructor args doesn't work
```

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.14;

contract Mapping {
    // Mapping from address to uint
    mapping(address => uint) public myMap;

    function get(address _addr) public view returns (uint) {
        // Mapping always returns a value.
        // If the value was never set, it will return the default value.
        return myMap[_addr];
    }

    function set(address _addr, uint _i) public {
        // Update the value at this address
        myMap[_addr] = _i;
    }

    function remove(address _addr) public {
        // Reset the value to the default value.
        delete myMap[_addr];
    }
}

contract NestedMapping {
    // Nested mapping (mapping from address to another mapping)
    mapping(address => mapping(uint => bool)) public nested;

    function get(address _addr1, uint _i) public view returns (bool) {
        // You can get values from a nested mapping
        // even when it is not initialized
        return nested[_addr1][_i];
    }

    function set(address _addr1, uint _i, bool _boo) public {
        nested[_addr1][_i] = _boo;
    }

    function remove(address _addr1, uint _i) public {
        delete nested[_addr1][_i];
    }
}
```

### LINKED ISSUE #851: Cairo dependency upgrade
Update Warp's cairo depedency
Will require updating the CI files, warp_venv.sh and requirements.txt

### PR DESCRIPTION
**Pull request by swapnilraj**
Closes #829
Closes #854
Closes #828
Closes #851

### CODE REVIEW

**Comment by piwonskp** [comment]
The "Closes" should be a comma-separated list

**Comment by JorikSchellekens** [comment]
I don't think #854 is the correct issue

**Comment by swapnilraj** [comment]
> The "Closes" should be a comma-separated list

thanks for correcting, Github I expected better

File: src/io.ts [hunk 1]
```diff
@@ -89,7 +89,7 @@ export function outputResult(
     );
     fs.outputFileSync(fullCodeOutPath, code);
 
-    if (options.formatCairo || options.dev) {
+    if (options.formatCairo /* || options.dev : Cairo-format is disabled, as it has a bug */) {
```
Comment (JorikSchellekens) [inline src/io.ts]: Should this not be disabled completely in the case that the tool itself has a bug?

**Comment by piwonskp** [comment]
> thanks for correcting, Github I expected better

Actually github handles newline separated as well as comma separated. I've just checked that on another repo. It just doesn't work on warp repo / this PR. I'm gonna make some more tests

**Comment by piwonskp** [comment]
Oh I see, you've made a PR to a side branch. Closing keywords work only for PRs to the default branch

**Review by rjnrohit — APPROVED** [review]

**Comment by rjnrohit** [comment]
Don't you want to merge this PR to `develop` branch?

**Comment by swapnilraj** [comment]
> Don't you want to merge this PR to `develop` branch?

No my PR uses stuff from cli_test so we can merge `cli_test` first and then Github will atuomatically change the target

File: .github/workflows/build.yml [hunk 2]
```diff
@@ -40,7 +40,7 @@ jobs:
         run: |
           yarn lint
           black starknet-testnet/ --check --verbose --diff --color
-          find warplib/ -iname *.cairo -exec cairo-format -c {} +
+        # find warplib/ -iname *.cairo -exec cairo-format -c {} +
```
Comment (piwonskp) [inline .github/workflows/build.yml:43]: Why would we keep that? (or why is it not needed anymore?)

Comment (piwonskp) [reply .github/workflows/build.yml:43]: Oh I see there's a comment below explaining that

File: tests/cli/utils.ts [hunk 3]
```diff
@@ -1,3 +1,28 @@
+import { sh } from '../util';
+import * as path from 'path';
+
+export const wallet = 'starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount';
+export const gatewayURL = 'http://127.0.0.1:5050';
+export const network = 'alpha-goerli';
+export const starkNetAccountDir = path.resolve(__dirname, '.');
+export const warpBin = path.resolve(__dirname, '..', '..', 'bin', 'warp');
```
Comment (piwonskp) [inline tests/cli/utils.ts]: let's keep consts uppercase snake case

File: tests/cli/noArgsDeploy.test.ts [hunk 4]
```diff
@@ -0,0 +1,202 @@
...
+    const contract_address = extractFromStdout(stdout, CONTRACT_ADDRESS_REGEX);
+    const txHash = extractFromStdout(stdout, TX_HASH_REGEX);
+
+    expect(txFeeEth).to.not.be.undefined;
+    expect(txFeeWei).to.not.be.undefined;
+    expect(contract_address).to.not.be.undefined;
+    expect(txHash).to.not.be.undefined;
+
+    const res = await sh(
+      `${warpBin} status ${txHash} --network ${network} --gateway_url ${gatewayURL} --feeder_gateway_url ${gatewayURL}`,
```
Comment (piwonskp) [inline tests/cli/noArgsDeploy.test.ts]: Imo a function `runWarpWithStarknetDefaults` or a string `STARKNET_DEFAULT_OPTIONS` would improve the readability of shell commands

File: tests/cli/noArgsDeploy.test.ts [hunk 5]
```diff
@@ -0,0 +1,202 @@
...
+    );
+
+    expect(res.stderr).to.be.empty;
+    expect(res.stdout).to.not.be.empty;
```
Comment (piwonskp) [inline tests/cli/noArgsDeploy.test.ts:101]: Why don't we use error codes? They're less sensitive. Example: tests fail when ran with the debugger as it prints some information to the stderr

File: docker.env [hunk 6]
```diff
@@ -2,6 +2,5 @@ STARKNET_NETWORK=alpha-goerli
 STARKNET_WALLET=starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount
 STARKNET_ACCOUNT_DIR=/usr/src/warp/.starknet_accounts_devnet
 
-# Doesn't work (Cairo 0.10.0, 0.10.1)
-# STARKNET_GATEWAY_URL=http://devnet:5050
-# STARKNET_FEEDER_GATEWAY_URL=http://devnet:5050
+STARKNET_GATEWAY_URL=http://devnet:5050
+STARKNET_FEEDER_GATEWAY_URL=http://devnet:5050
```
Comment (piwonskp) [inline docker.env:6]: Are you sure it is fixed? I've created [the issue](https://github.com/starkware-libs/cairo-lang/issues/118) in cairo repository and it is not resolved

Comment (swapnilraj) [reply docker.env:6]: Warp now has the feeder gateway url and the gateway url options and it picks them up from the environment and passes them explicitly to the starknet cli

File: tests/cli/noArgsDeploy.test.ts (hunk 5 above)
Comment (swapnilraj) [reply tests/cli/noArgsDeploy.test.ts:104]: Good point, changed from stderr detection to exit code

File: tests/cli/noArgsDeploy.test.ts (hunk 4 above)
Comment (swapnilraj) [reply tests/cli/noArgsDeploy.test.ts]: abstracted the network options and the account options so its a lot cleaner now

File: tests/cli/noArgsDeploy.test.ts (hunk 5 above)
Comment (swapnilraj) [reply tests/cli/noArgsDeploy.test.ts:101]: exec doesn't give an exit code if the process didn't fail and I realised it doesn't make sense to check the stderr or exit code because if the process fails then sh will fail and the test will fail altogether

**Review by JorikSchellekens — APPROVED** [review]

File: src/io.ts (hunk 1 above)
Comment (swapnilraj) [reply src/io.ts:92]: Do you mean remove the flag completely? I think its okay to suspend its actions for now because Cairo 1.0 compiler will have its own flag and in the upgrade we can enable it again

Comment (swapnilraj) [reply src/io.ts]: yes fixed
